#!/usr/bin/env python3

import RPi.GPIO as GPIO
from Cycle import Cycle as Cycle
import time

minutes_per_day = 24 * 60 * 60

# Setup GPIO pins as outputs/inputs
GPIO.setmode(GPIO.BOARD)
water_timer = Cycle(minutes_per_day / 4, 15 * 60, GPIO, pin=18)
anothertimer = Cycle(minutes_per_day / 4, 15 * 60, GPIO, pin=23)

while True:
    water_timer.check_pin()
    anothertimer.check_pin()
    time.sleep(1)

GPIO.cleanup()
