#!/usr/bin/env python 

#Import GPIO Module
import RPi.GPIO as GPIO
# Import sleep Module for timing
from time import sleep
# Configures how we are describing our pin numbering
GPIO.setmode(GPIO.BCM)
# Disable Warnings
GPIO.setwarnings(False)
# Set the GPIO pins that are required
OutputPins = [22, 23, 24, 25]
#Set the GPIO pins to outputs and set them to off
for i in OutputPins: GPIO.setup(i, GPIO.OUT) GPIO.output(i, False) try: 
    while (True):
# Step through each GPIO pin and set On
        for i in OutputPins: GPIO.output(i, True)
# Sleep for 5 seconds
            sleep(5) GPIO.output(i, False) except KeyboardInterrupt:
# catches the ctrl-c command, breaks the loop above and turns the relays 
# off
    For i in OutputPins:
        GPIO.output(i, False)
